### ISSUE TITLE
Broken persistent build

### ISSUE THREAD

**Issue by 6d6178667269747a** [qzed/aarch64-arch-mkimg#2]
There is a missing dereference link copy argument "-L".

https://github.com/linux-surface/aarch64-arch-mkimg/blob/1f2b12a3ddd504976c22012ce37db022145e856f/lib/base/rootfs.sh#L14

Without I get:

~/workspace/aarch64-arch-mkimg (main ✔) sudo podman run --rm --privileged -v /dev:/dev -v "${PWD}/build":/build aarch64_builder persistent
podman===> Preparing sources...
 --> Importing Arch Linux ARM GPG key...
 --> Downloading 'ArchLinuxARM-aarch64-latest.tar.gz'...
 --> Verifying 'ArchLinuxARM-aarch64-latest.tar.gz'...
 --> Verification passed
 --> Extracting 'ArchLinuxARM-aarch64-latest.tar.gz'...
===> Preparing rootfs...
 --> Copying base files...
cp: cannot overwrite directory '//build/rootfs/./boot' with non-directory
cp: cannot overwrite directory '//build/rootfs/./etc' with non-directory

**Comment by qzed** [comment]
Thanks for reporting! Fixed in da0fb202bd227ca1dca0729ca99c58f13c649ece.
