### ISSUE TITLE
Error chroot: failed to run command 

### ISSUE THREAD

**Issue by rexido1** [qzed/aarch64-arch-mkimg#4]
chroot: failed to run command ‘/root/aarch64-archimg/lib/_setup.sh’: Exec format error

**Comment by qzed** [comment]
See https://github.com/linux-surface/aarch64-arch-mkimg#running-on-an-x86-host. You'll have to set up `qemu-user-static` for `arm64` emulation.

**Comment by rexido1** [comment]
Thank you very much )
Problem solved)
