### ISSUE TITLE
Working: Archlinux Arm Repo and mirrors issues

### ISSUE THREAD

**Issue by F9Alejandro** [qzed/aarch64-arch-mkimg#7]
Leaving this open as a reminder to try working on this and see about getting it working properly.

**Comment by F9Alejandro** [comment]
Mirror seems to be working properly and I have been able to change out the mirrorlist to favor my mirror first before going to the archlinuxarm mirror link. 

Seems to have downloaded with little issue, extensive testing is required. Possibly will need to get another node and start load balancing.

**Comment by qzed** [comment]
I hadn't really noticed any issues with the standard mirrors so far. Probably because I don't really pay attention when updating. Anyways, you should bring this up with the ALARM folks.

> Mirror seems to be working properly and I have been able to change out the mirrorlist to favor my mirror first before going to the archlinuxarm mirror link.

Just to understand: Did you set up your own mirror or just adjust the mirror list to prefer one close to you / with better performance?

**Comment by F9Alejandro** [comment]
I created one using a server I have from Linode. I also added the mirror from Berkeley.edu as well just to be sure it is stable. Normal archlinux is fine with grabbing. archlinuxarm is not however. I have had the build fail numerous times because of the mirror timeout errors or just dying entirely.

#8 should fix this, feel free to push it into a new branch just to test and be sure it works properly. If it does you may even be able to make precompiled images.

**Comment by qzed** [comment]
As I've said in the other discussion, this seems to be exclusively an issue with the packages from our linux-surface repo (unless the error reporting is completely wrong somehow). I haven't seen the official alarm repo fail yet.

**Comment by F9Alejandro** [comment]
Closing this out as branch "ci: build feature" is working with the changes made to it.
